/**
 * Ask upstream what sites it knows about, and write down the answer.
 *
 *     npm run sync                 # fetch prajwalch/TorrentSearch@main
 *     npm run sync -- --ref v1.2   # a tag or commit instead
 *     npm run sync -- --from DIR   # a local checkout, no network
 *     npm run sync -- --check      # fail if upstream/providers.json is stale
 *
 * This is the half of the project that runs on a clock. It writes two files:
 *
 *   upstream/providers.json  the census, every site upstream knows about, and
 *                            everything upstream states outright about it
 *   upstream/COVERAGE.md     the difference between that census and the
 *                            descriptors in `catalogue/`
 *
 * The census is the thing that keeps this project from freezing. In the
 * project this one replaces, the catalogue lived inside the Worker, so it
 * could only ever contain what somebody had typed into a source file, and a
 * deployed Worker was a photograph of the day it was pasted. Here the sites
 * come from a project whose whole business is keeping up with them, and a
 * sync is how that reaches us: a site upstream adds turns up in COVERAGE.md as
 * missing, a site that moves turns up as drifted, a site that dies turns up as
 * dropped. Nobody has to notice on their own.
 *
 * What a sync does not do is write descriptors. Upstream parses each site with
 * a hand-written Kotlin class, and translating one into a descriptor is a
 * judgement about how a page is laid out, see `catalogue/README.md`. So the
 * sync tells you what to write and what has changed under you; it does not
 * pretend to write it.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { UPSTREAM, fetchProviders, readProviders } from "./upstream.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "..", "..");
const CATALOGUE = join(REPO, "catalogue");
const CENSUS_PATH = join(REPO, "upstream", "providers.json");
const COVERAGE_PATH = join(REPO, "upstream", "COVERAGE.md");

/** The descriptors we hold, by the upstream id each one claims. */
export function catalogue() {
  if (!existsSync(CATALOGUE)) return [];
  return readdirSync(CATALOGUE)
    .filter((file) => file.endsWith(".json"))
    .map((file) => ({ file, ...JSON.parse(readFileSync(join(CATALOGUE, file), "utf8")) }))
    .sort((a, b) => a.id.localeCompare(b.id));
}

/** The host part of a URL, without `www.`, or null if it is not a URL. */
function host(url) {
  try {
    return new URL(url).host.replace(/^www\d*\./, "");
  } catch {
    return null;
  }
}

/**
 * What the census says that the catalogue does not yet reflect.
 *
 * Four kinds of difference, and only the first is a gap in coverage:
 *
 *   missing  upstream knows this site; we have no descriptor for it
 *   drifted  we have one, but upstream now names a host none of our origins do
 *   dropped  we have one for a site upstream no longer carries
 *   held     ours by choice, never upstream's, a Torznab index, say
 */
export function compare(census, descriptors) {
  const byId = new Map(census.map((entry) => [entry.id, entry]));
  const covered = new Set(descriptors.map((entry) => entry.upstream).filter(Boolean));

  const missing = census.filter((entry) => !covered.has(entry.id));
  const dropped = descriptors.filter((entry) => entry.upstream && !byId.has(entry.upstream));
  const held = descriptors.filter((entry) => !entry.upstream);

  const drifted = [];
  for (const descriptor of descriptors) {
    const upstream = descriptor.upstream && byId.get(descriptor.upstream);
    if (!upstream || !upstream.site) continue;
    const theirs = host(upstream.site);
    const ours = [descriptor.site, ...(descriptor.origins || [])].map(host).filter(Boolean);
    if (theirs && ours.length && !ours.includes(theirs)) {
      drifted.push({ id: descriptor.id, upstream: descriptor.upstream, theirs, ours });
    }
  }

  return { missing, drifted, dropped, held };
}

const table = (rows) => (rows.length ? rows.join("\n") : "_none_");

function coverageMarkdown(census, descriptors, { sha, committed_at, synced_at }) {
  const { missing, drifted, dropped, held } = compare(census, descriptors);
  const carried = descriptors.length - held.length;

  return `# Coverage

Generated by \`npm run sync\`. Do not edit.

Upstream is [${UPSTREAM.owner}/${UPSTREAM.repo}](${UPSTREAM.url}) at
[\`${sha.slice(0, 12)}\`](${UPSTREAM.url}/commit/${sha})${committed_at ? ` (committed ${committed_at})` : ""},
read ${synced_at}.

Upstream carries **${census.length}** sites. This project has descriptors for
**${carried}** of them${held.length ? `, plus ${held.length} of its own` : ""}.

## Missing: upstream has these, we do not

${table(
  missing.map(
    (entry) =>
      `- \`${entry.id}\`: [${host(entry.site) || entry.site || "?"}](${entry.site}) · ${entry.shape}${entry.cloudflare ? " · behind Cloudflare" : ""}${entry.unsafe ? " · upstream marks unsafe" : ""}${entry.enabled_by_default ? " · **on by default upstream**" : ""}`,
  ),
)}

## Drifted: upstream now names a host we do not

${table(drifted.map((entry) => `- \`${entry.id}\`: upstream says \`${entry.theirs}\`; we ask ${entry.ours.map((h) => `\`${h}\``).join(", ")}`))}

## Dropped: we have these, upstream no longer does

${table(dropped.map((entry) => `- \`${entry.id}\`: was \`${entry.upstream}\``))}

## Held: ours, never upstream's

${table(held.map((entry) => `- \`${entry.id}\``))}
`;
}

/**
 * The census as it will be written.
 *
 * `synced_at` is deliberately not part of what `--check` compares: a sync that
 * finds upstream unchanged should not produce a diff, or a scheduled sync would
 * commit a new timestamp every time it ran and say nothing by doing so.
 */
function censusFile({ sha, committed_at, providers, synced_at }) {
  return {
    "//": `Every site ${UPSTREAM.owner}/${UPSTREAM.repo} knows about, and everything it states outright about each. Written by \`npm run sync\`. Data only.`,
    upstream: { repo: `${UPSTREAM.owner}/${UPSTREAM.repo}`, url: UPSTREAM.url, commit: sha, committed_at, dir: UPSTREAM.dir },
    synced_at,
    count: providers.length,
    providers,
  };
}

const stableBody = (census) => JSON.stringify({ ...census, synced_at: null }, null, 2);

export async function sync({ ref = "main", from = null, check = false, now = new Date(), log = console.log } = {}) {
  let sha;
  let committed_at;
  let sources;

  if (from) {
    const dir = join(from, UPSTREAM.dir);
    const at = existsSync(dir) ? dir : from;
    sources = Object.fromEntries(
      readdirSync(at)
        .filter((file) => file.endsWith(".kt"))
        .map((file) => [file, readFileSync(join(at, file), "utf8")]),
    );
    sha = ref === "main" ? "local" : ref;
    committed_at = null;
    log(`read ${Object.keys(sources).length} sources from ${at}`);
  } else {
    log(`fetching ${UPSTREAM.owner}/${UPSTREAM.repo}@${ref}…`);
    ({ sha, committed_at, sources } = await fetchProviders(ref));
    log(`read ${Object.keys(sources).length} sources at ${sha.slice(0, 12)}`);
  }

  const providers = readProviders(sources);
  if (!providers.length) throw new Error("upstream answered, but no provider carried an id; has its layout changed?");

  const synced_at = now.toISOString().replace(/\.\d+Z$/, "Z");
  const census = censusFile({ sha, committed_at, providers, synced_at });
  const descriptors = catalogue();

  if (check) {
    const before = existsSync(CENSUS_PATH) ? JSON.parse(readFileSync(CENSUS_PATH, "utf8")) : null;
    if (!before || stableBody(before) !== stableBody(census)) {
      throw new Error("upstream/providers.json is stale; run `npm run sync` and commit the result");
    }
    log(`upstream/providers.json is current: ${providers.length} sites at ${sha.slice(0, 12)}`);
    return { census, descriptors, changed: false };
  }

  mkdirSync(dirname(CENSUS_PATH), { recursive: true });
  const before = existsSync(CENSUS_PATH) ? readFileSync(CENSUS_PATH, "utf8") : "";
  const after = `${JSON.stringify(census, null, 2)}\n`;
  const changed = stableBody(before ? JSON.parse(before) : {}) !== stableBody(census);

  // A sync that finds upstream unchanged must leave no trace, or the scheduled
  // one commits every week to report that nothing happened. So the census keeps
  // the date it was actually last new, and the coverage report quotes that
  // date rather than the wall clock, which would otherwise be the one thing
  // that differed in an otherwise identical file.
  writeFileSync(CENSUS_PATH, changed ? after : before || after);
  const effective = changed || !before ? synced_at : JSON.parse(before).synced_at;
  writeFileSync(COVERAGE_PATH, coverageMarkdown(providers, descriptors, { sha, committed_at, synced_at: effective }));

  const { missing, drifted, dropped } = compare(providers, descriptors);
  log(`${providers.length} sites upstream · ${descriptors.length} descriptors here`);
  if (missing.length) log(`  ${missing.length} missing, see upstream/COVERAGE.md`);
  if (drifted.length) log(`  ${drifted.length} drifted: ${drifted.map((e) => e.id).join(", ")}`);
  if (dropped.length) log(`  ${dropped.length} dropped: ${dropped.map((e) => e.id).join(", ")}`);
  log(changed ? "upstream/providers.json updated" : "upstream unchanged");

  return { census, descriptors, changed };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const argv = process.argv.slice(2);
  const flag = (name) => {
    const at = argv.indexOf(`--${name}`);
    return at === -1 ? null : argv[at + 1];
  };
  await sync({ ref: flag("ref") || "main", from: flag("from"), check: argv.includes("--check") }).catch((error) => {
    console.error(String(error.message || error));
    process.exit(1);
  });
}
